// <auto-generated />
using System;
using ASP.Net.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASP.Net.Migrations
{
    [DbContext(typeof(BillContext))]
    [Migration("20231116182444_BillCreationDate")]
    partial class BillCreationDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("ASP.Net.Models.Bill.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ColdWaterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ElectricityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HotWaterAndHeatingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Overpayment")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ColdWaterId");

                    b.HasIndex("ElectricityId");

                    b.HasIndex("HotWaterAndHeatingId");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("ASP.Net.Models.Bill.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("ToPay")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("ASP.Net.Models.Bill.Bill", b =>
                {
                    b.HasOne("ASP.Net.Models.Bill.Service", "ColdWater")
                        .WithMany()
                        .HasForeignKey("ColdWaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASP.Net.Models.Bill.Service", "Electricity")
                        .WithMany()
                        .HasForeignKey("ElectricityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASP.Net.Models.Bill.Service", "HotWaterAndHeating")
                        .WithMany()
                        .HasForeignKey("HotWaterAndHeatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ColdWater");

                    b.Navigation("Electricity");

                    b.Navigation("HotWaterAndHeating");
                });
#pragma warning restore 612, 618
        }
    }
}
